# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "345fcfded4c3f6b3f8d8ab521cf7d9a4"
name = "ReturnHood"
handle = "returnhood-2"
application_url = "https://decision-approach-automobile-mitchell.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f518e33a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_orders,read_price_rules,read_products,read_themes,write_discounts,write_orders,write_price_rules,write_products,write_themes"

[auth]
redirect_urls = [
  "https://decision-approach-automobile-mitchell.trycloudflare.com/auth/callback",
  "https://decision-approach-automobile-mitchell.trycloudflare.com/auth/shopify/callback",
  "https://decision-approach-automobile-mitchell.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
